version: '2'

services:
    tyk_redis:
        image: redis:3.0.7-alpine
        hostname: redis
        #ports:
        #    - "6379:6379"
        networks:
            gateway:
                aliases:
                    - redis
    tyk_mongo:
        image: mongo:3.3
        command: ["mongod", "--smallfiles"]
        hostname: mongo
        #ports:
        #    - "27017:27017"
        networks:
            gateway:
                aliases:
                    - mongo
    tyk_dashboard:
        image: tykio/tyk-dashboard:v0.9.7.2
        ports:
            - "3000:3000"
            - "5000:5000"
        volumes:
            - ./tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
        networks:
            - gateway
    tyk_gateway:
        image: tykio/tyk-gateway:v1.8
        ports:
            - "8888:8080"
            - "8889:8080"
        volumes:
            - ./tyk.conf:/opt/tyk-gateway/tyk.conf
        networks:
            - gateway

networks:
    gateway:
